### ISSUE TITLE
Connection is broken or need instructions on url format

### ISSUE THREAD

**Issue by ahgray** [Igalia/libreplanapp#1]
No one seems to be able to connect. Either something is broken, or the app should have better instructions regarding what its expecting for a URL.

**Comment by kwoot** [comment]
localhost:8080/libreplan should work.

**Comment by ahgray** [comment]
Thanks for the quick response. That seems to work. Perhaps adding an indication in the app about the format would help others, all the reviews in the play store are about people being unable to connect. For the record i did have to change host name to IP, but that could be a DNS issue on my end.
